import Vue from "vue";
import KbButton from "@/components/button/index.vue";
import KbNavbar from "@/components/navbar/index.vue";
import KbDropdown from "@/components/dropdown/index.vue";
import KbTable from "@/components/table/index.vue";
import KbText from "@/components/text/index.vue";
import KbIcon from "@/components/icon/index.vue";
import KbLabel from "@/components/label/index.vue";
import KbBadge from "@/components/badge/index.vue";
import KbPopup from "@/components/popup/index.vue";
Vue.component("KbButton", KbButton);
Vue.component("KbNavbar", KbNavbar);
Vue.component("KbDropdown", KbDropdown);
Vue.component("KbTable", KbTable);
Vue.component("KbText", KbText);
Vue.component("KbIcon", KbIcon);
Vue.component("KbLabel", KbLabel);
Vue.component("KbBadge", KbBadge);
Vue.component("KbPopup", KbPopup);
